import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Enoch Olaoluwa Portfolio",
  description: "Generated by create next app",
};

import { ThemeProvider } from "@/components/theme-provider";
import { PreloaderWrapper } from "@/components/preloader-wrapper";
import { SmoothScrolling } from "@/components/smooth-scrolling";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col overflow-x-hidden px-4 md:px-8">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SmoothScrolling>
            <PreloaderWrapper>
              {children}
            </PreloaderWrapper>
          </SmoothScrolling>
        </ThemeProvider>
      </body>
    </html>
  );
}
